### ISSUE TITLE
ValidateTransferError: invalid memo keys

### ISSUE THREAD

**Issue by Luchanso** [anza-xyz/solana-pay#230]
I got some error for valid transaction:
```log
ValidateTransferError: invalid memo keys
    at validateMemo (D:\dev\ssr\node_modules\@solana\pay\src\validateTransfer.ts:97:40)
    at D:\dev\ssr\node_modules\@solana\pay\src\validateTransfer.ts:88:9
    at Generator.next (<anonymous>)
    at fulfilled (D:\dev\ssr\node_modules\@solana\pay\lib\cjs\validateTransfer.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Simple playground: https://codesandbox.io/p/devbox/hardcore-mclaren-qtz7zg?file=%2Findex.js%3A28%2C7

function `validateTransfer(...) ` not correct work when pass memo string, I think it's can be bug on: https://github.com/anza-xyz/solana-pay/blame/master/core/src/validateTransfer.ts#L97 because "instruction.keys" must contain single key about Signer
![image](https://github.com/anza-xyz/solana-pay/assets/2098777/9567d22d-3a0e-4751-abef-92c0ec1c4ca9)

**Comment by moulin-louis** [comment]
Hey 👋 I’m facing the same issue, did you manage to solve this ? Or the bug is still around ? 
Thanks a lot !

**Comment by Luchanso** [comment]
Workaround: create this file with commented this string in your local project, and use this function from it:

https://gist.github.com/Luchanso/2b3e7c4f7d9ce8a6128ebe7ed004cec8#file-validate-ts-L98
